### PR TITLE
Added ability change table name of gallery. Fix migration. Update README.

### PR DESCRIPTION
**Pull request by bupy7**
Hi! Merge, please! =)

### CODE REVIEW

**Comment by zxbodya** [comment]
Hi, thanks for an idea, probably this would be useful in some cases.
But I do not like an implementation... moving this to global app params is quite weird for me...

As a better option why not jest make `tableName` property in gallery behaviour public and allow user to change it when needed?

---

About migrations, I think that running migrations from extension folder is really bad idea -  person(or a script) who will deploy you application - should know only that he needs to run application migrations(but he should not be required to know about all extensions... ). In other words - it is library, not a plugin that can be installed by user.

So it is better to extend migration from extension, but even better copy it (for ease of upgrading in case of migration change)... by convenience migrations should be written once, and not changed in future(except quite rare cases) 

About idea of using application params in migration - it is even worse... migrations should not depend parameters, and if possible even on codebase(to have possibility to migrate to any database version).

about tableName in migrations - I think, adding public tableName property to migration would be enough.

**Comment by bupy7** [comment]
hm...ok) please make ability change table name to your extension.

**Comment by zxbodya** [comment]
done.

**Comment by bupy7** [comment]
Воо! Вот сейчас ахуено просто. Уважуха прост от пацанов с района. С меня горсть сэмак. =)

**Pull request closed without merging**
